# Generated by Django 5.2 on 2025-05-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(
                default=222, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
