# Generated by Django 5.2 on 2025-05-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epsoft", "0002_alter_useraccount_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permission for this user.",
                related_name="user_accounts",
                to="auth.permission",
            ),
        ),
    ]
