# Generated by Django 5.2 on 2025-05-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0003_alter_useraccount_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("UAN", models.IntegerField(blank=True, null=True)),
                ("SINo", models.IntegerField(blank=True, null=True)),
                ("aadhar", models.IntegerField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("DateOfAppointment", models.DateField()),
            ],
        ),
    ]
