# Generated by Django 5.2 on 2025-05-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0004_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="inputnumber",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
