# Generated by Django 5.2 on 2025-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0006_alter_staff_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="DateOfAppointment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
