# Generated by Django 5.2 on 2025-05-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0007_alter_staff_dateofappointment_alter_staff_dob"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
