# Generated by Django 5.2 on 2025-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0008_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.TextField(blank=True, null=True)),
                ("UAN", models.IntegerField(blank=True, null=True)),
                ("SINo", models.IntegerField(blank=True, null=True)),
                ("aadhar", models.IntegerField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("DateOfAppointment", models.TextField(blank=True, null=True)),
                ("inputnumber", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
