# Generated by Django 5.2 on 2025-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0009_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="UAN",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="aadhar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="inputnumber",
            field=models.TextField(blank=True, null=True),
        ),
    ]
