# Generated by Django 5.2 on 2025-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0010_alter_staff_uan_alter_staff_aadhar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="SINo",
        ),
    ]
