# Generated by Django 5.2 on 2025-05-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0011_remove_staff_sino"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="accountnumber",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="ifsccode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
