# Generated by Django 5.2 on 2025-05-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0012_staff_accountnumber_staff_ifsccode"),
    ]

    operations = [
        migrations.CreateModel(
            name="staffwage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staffattendence", models.IntegerField(default=0)),
                ("wage", models.TextField(blank=True, null=True)),
                ("epf", models.TextField(blank=True, null=True)),
                ("esi", models.TextField(blank=True, null=True)),
                ("totalwage", models.TextField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
                (
                    "staffid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="epsoft.staff"
                    ),
                ),
            ],
        ),
    ]
