# Generated by Django 5.2 on 2025-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0014_remove_staffwage_epf_remove_staffwage_esi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffwage",
            name="wage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
