# Generated by Django 5.2 on 2025-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epsoft", "0015_alter_staffwage_wage"),
    ]

    operations = [
        migrations.AddField(
            model_name="epfcalculation",
            name="date",
            field=models.TextField(blank=True, null=True),
        ),
    ]
